# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    merklet = builder {
      name = "merklet";
      version = "2.0.0";
      src = fetchHex {
        pkg = "merklet";
        version = "2.0.0";
        sha256 = "sha256-teho2ll5+bPD5Oi4FxqlwWeGjjVJW4FzHJPYOC/dMng=";
      };
      beamDeps = [ ];
    };
  };
in self
